name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Application version"
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "25"

      - name: Install Dependencies
        run: npm ci

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: |
          node version.js ${{ steps.version.outputs.version }} vue
          node version.js ${{ steps.version.outputs.version }} json
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
